/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testsobel_nativeSobelFilter */

#ifndef _Included_com_example_testsobel_nativeSobelFilter
#define _Included_com_example_testsobel_nativeSobelFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testsobel_nativeSobelFilter
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_testsobel_nativeSobelFilter_test
  (JNIEnv *, jobject);

/*
 * Class:     com_example_testsobel_nativeSobelFilter
 * Method:    sobelFilter
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_example_testsobel_nativeSobelFilter_sobelFilter
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
